# version: '3.8'

# services:
#   # Our PostgreSQL Database Service
#   db:
#     image: postgres:15-alpine
#     container_name: sajag_db
#     restart: always
#     environment:
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#       POSTGRES_DB: ${DB_NAME}
#     ports:
#       - '5432:5432'
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     # --- ADD THIS HEALTHCHECK SECTION ---
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
#       interval: 5s
#       timeout: 5s
#       retries: 5

#   # Our Node.js Application Service
#   # Our Node.js Application Service
#   app:
#     build: .
#     container_name: sajag_app
#     restart: always
#     # ADD THIS COMMAND ATTRIBUTE
#     command: sh -c "npm start > /usr/src/app/output.log 2>&1"
#     depends_on:
#       db:
#         condition: service_healthy
#     ports:
#       - '${PORT}:${PORT}'
#     volumes:
#       - .:/usr/src/app
#       - /usr/src/app/node_modules
#     env_file:
#       - .env

# volumes:
#   postgres_data:


version: '3.8'

services:
  # Our PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    container_name: sajag_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Our Node.js Application Service
  app:
    build: .
    container_name: sajag_app
    restart: always
    # Niche wali line maine hata di hai taaki logs terminal par dikhein
    # command: sh -c "npm start > /usr/src/app/output.log 2>&1" 
    # ADD THIS COMMAND ATTRIBUTE
    command: npm start
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env

volumes:
  postgres_data: